# Loads default set of integrations. Do not remove
default_config:

homeassistant:
  packages: !include_dir_named packages/
  media_dirs:
    local: /media
    www: /config/www

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

#################################################################
## Includes
#################################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modbus: # https://www.home-assistant.io/integrations/modbus/
  - type: tcp
    host: !secret modbus_heatpump_ip
    port: 502
    name: "modbus_pac"
    delay: 1 # time to delay sending messages in seconds after connecting
    message_wait_milliseconds: 100
    timeout: 10
    sensors:
      - name: "PAC External Temperature"
        address: 1003 # address -1 compare to the modbus register map (mbpoll)
        input_type: holding
        data_type: int16
        scale: 0.1
        precision: 1
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "PAC Temperature ECS"
        address: 1001
        input_type: holding
        data_type: int16
        scale: 0.1
        precision: 1
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "PAC Circuit Temperature"
        address: 1004
        input_type: holding
        data_type: int16
        scale: 0.1
        precision: 1
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "PAC State"
        address: 1021
        input_type: holding
        data_type: int16

      # PAC registers 1001-1114
      - name: "PAC address 1001"
        address: 1001
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1003"
        address: 1003
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1004"
        address: 1004
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1005"
        address: 1005
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1006"
        address: 1006
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1007"
        address: 1007
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1015"
        address: 1015
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1016"
        address: 1016
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1017"
        address: 1017
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1021"
        address: 1021
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1023"
        address: 1023
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1028"
        address: 1028
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1029"
        address: 1029
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1100"
        address: 1100
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1101"
        address: 1101
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1102"
        address: 1102
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 1111"
        address: 1111
        input_type: holding
        data_type: int16
        state_class: measurement

      # PAC register 6001-6039
      - name: "PAC address 6001"
        address: 6001
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6002"
        address: 6002
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6003"
        address: 6003
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6004"
        address: 6004
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6005"
        address: 6005
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6008"
        address: 6008
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6009"
        address: 6009
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6010"
        address: 6010
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6011"
        address: 6011
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6012"
        address: 6012
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6013"
        address: 6013
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6014"
        address: 6014
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6015"
        address: 6015
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6016"
        address: 6016
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6017"
        address: 6017
        input_type: holding
        data_type: int16
        state_class: measurement
      - name: "PAC address 6018"
        address: 6018
        input_type: holding
        data_type: int16
        state_class: measurement

      # PAC registers 2000-2039
      # /!\ Not interesting registers. These look like mode or settings are are always constant...
      # - name: "PAC address 2000"
      #   address: 2000
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2001"
      #   address: 2001
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2002"
      #   address: 2002
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2003"
      #   address: 2003
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2004"
      #   address: 2004
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2005"
      #   address: 2005
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2006"
      #   address: 2006
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2007"
      #   address: 2007
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2008"
      #   address: 2008
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2009"
      #   address: 2009
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2010"
      #   address: 2010
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2011"
      #   address: 2011
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2012"
      #   address: 2012
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2013"
      #   address: 2013
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2014"
      #   address: 2014
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2015"
      #   address: 2015
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2016"
      #   address: 2016
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2017"
      #   address: 2017
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2018"
      #   address: 2018
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2019"
      #   address: 2019
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2020"
      #   address: 2020
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2021"
      #   address: 2021
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2022"
      #   address: 2022
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2023"
      #   address: 2023
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2024"
      #   address: 2024
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2025"
      #   address: 2025
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2026"
      #   address: 2026
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2027"
      #   address: 2027
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2028"
      #   address: 2028
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2029"
      #   address: 2029
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2030"
      #   address: 2030
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2031"
      #   address: 2031
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2032"
      #   address: 2032
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2033"
      #   address: 2033
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2034"
      #   address: 2034
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2035"
      #   address: 2035
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2036"
      #   address: 2036
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2037"
      #   address: 2037
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2038"
      #   address: 2038
      #   input_type: holding
      #   data_type: int16
      # - name: "PAC address 2039"
      #   address: 2039
      #   input_type: holding
      #   data_type: int16

zeroconf:

mysql_query:
  mysql_host: !secret mysql_host
  mysql_port: !secret mysql_port
  mysql_username: !secret mysql_username
  mysql_password: !secret mysql_password
  mysql_db: rtttl
  mysql_collation: utf8mb4_general_ci

recorder:
  db_url: !secret db_url
  exclude:
    entities:
      # Exclude any logging of the chosen light.
      - light.smart_bulb_kids_room
      # Exclude any logging of this color loop script.
      - automation.color_loop_kids_room
      - sensor.slzb_06_uptime
    entity_globs:
      - sensor.shelly_*_voltage
      - sensor.shelly_*_current
      # - sensor.shelly_*_power
      - sensor.shelly_*_frequency
      # - automation.nspanel_*_blueprint
      - sensor.haut_*
      - sensor.bas_*
      - sensor.shelly_*_temperature
      - sensor.nspanel_*_rssi
      - sensor.dream_machine_special_edition_*
      - sensor.sunrise_*

# This stops working in version 2027.2.0. Please address before upgrading.
# http:
#   server_port: 8087
#   use_x_forwarded_for: true
#   trusted_proxies:
#     - 127.0.0.1
#     - ::1
#     - 192.168.1.0/24

logger:
  default: info
  logs:
    homeassistant.components.automation.nspanel_parents_room_blueprint: warning
    homeassistant.components.automation.nspanel_kids_room_blueprint: warning
    homeassistant.components.automation.nspanel_guest_room_blueprint: warning
    homeassistant.components.automation.nspanel_living_room_blueprint: warning
    homeassistant.components.automation.nspanel_tv_room_blueprint: warning
    aioesphomeapi.reconnect_logic: warning

i_regul_heatpump:
  id: !secret i_regul_heatpump_id
  password: !secret i_regul_heatpump_password
  scan_interval: 300

import_statistics:

## Temporary disable because i_regul_heatpump is disabled

#sensor:
#  - platform: derivative
#    name: Heating power
#    source: sensor.i_regul_heatpump_heating_energy_consumption
#    unit: kW
#    time_window: "00:10:00"
#  - platform: derivative
#    name: Defrost power
#    source: sensor.i_regul_heatpump_defrost_energy_consumption
#    unit: kW
#    time_window: "00:10:00"
#  - platform: derivative
#    name: Cooling power
#    source: sensor.i_regul_heatpump_cooling_energy_consumption
#    unit: kW
#    time_window: "00:10:00"
#  - platform: derivative
#    name: ECS power
#    source: sensor.i_regul_heatpump_ecs_energy_consumption
#    unit: kW
#    time_window: "00:10:00"
#  - platform: derivative
#    name: Heat pump total power
#   source: sensor.i_regul_heatpump_total_energy_consumption
#   unit: kW
#   time_window: "00:10:00"

# logger:
#   logs:
#     homeassistant.components.utility_meter.sensor: debug

template:
  - binary_sensor:
      - name: "PAC State 0"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(1) > 0 }}
      - name: "PAC State 1"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(2) > 0 }}
      - name: "PAC State 2"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(4) > 0 }}
      - name: "PAC State 3"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(8) > 0 }}
      - name: "PAC State 4"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(16) > 0 }}
      - name: "PAC State 5"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(32) > 0 }}
      - name: "PAC State 6"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(64) > 0 }}
      - name: "PAC State 7"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(128) > 0 }}
      - name: "PAC State 8"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(256) > 0 }}
      - name: "PAC State 9"
        state: >
          {{ states('sensor.pac_state') | int | bitwise_and(512) > 0 }}
      - name: "PAC Address 1023 derivative positive"
        state: >
          {{ states('sensor.pac_address_1023_derivative') | float(0) > 0 }}
        delay_on:
          minutes: 2
        delay_off:
          minutes: 2

  # Test SEY with templated sensor (01-09-2025)
  - sensor:
      - name: "Total Water Consumption Test"
        unit_of_measurement: "m³"
        state: none
        device_class: water
        state_class: total

  #### Tracking time TV watching
  - sensor:
      - name: "Time TV watching"
        state: >
          {% if is_state('media_player.shield_2', 'on') %}
            {{ relative_time(states.media_player.shield_2.last_updated) }}
          {% endif %}

rest_command:
  notify_lametric:
    url: "http://192.168.1.10:8080/api/v2/widget/update/com.lametric.diy.devwidget/e2bbb2bb48d0499db222e82266893326"
    method: "post"
    username: !secret lametric_username
    password: !secret lametric_password
    content_type: "application/json"
    payload: '{ "frames" : [ { "icon": "{{ icon }}", "text" : "{{ text }}" } ] }'
