id: cooling_noon_to_sunset_kids_room
alias: Cooling ON at Noon and OFF 1h after Sunset (Kids Room)
trigger:
  - platform: time
    at: "12:00:00"
condition: []
action:
  - service: climate.turn_on
    target:
      entity_id: climate.nspanel_kids_room_thermostat  # <-- Replace with your climate entity

  - wait_template: >
      {{ now() >= state_attr('sun.sun', 'next_setting') | as_datetime + timedelta(hours=1) }}

  - service: climate.turn_off
    target:
      entity_id: climate.nspanel_kids_room_thermostat  # <-- Replace with your climate entity
mode: single