substitutions:
  # Settings - Editable values
  device_name: "nspanel-guest-room"
  friendly_name: "NSPanel Guest Room"
  wifi_ssid: !secret iot_wifi_ssid
  wifi_password: !secret iot_wifi_password
  ota_password: !secret ota_password
  nextion_update_url: !secret nspanel_url   # Optional
  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"
  cooler_relay: "1"
  include_action_wake_up: true     # Register the wake_up API action

# Customization area
##### My customization - Start #####
##### My customization - End ##### 

# Core and optional configurations
packages:
  network_diagnostics: !include 
    file: /config/esphome/common/network_diagnostics.yaml
    vars: 
      network_device_name: "${friendly_name}"
      
  remote_package:
    url: https://github.com/edwardtfn/NSPanel-Easy
    ref: latest
    refresh: 300s
    files:
      - esphome/nspanel_esphome_core.yaml
      - esphome/nspanel_esphome_standard.yaml
      - esphome/nspanel_esphome_addon_climate_dual.yaml
      - esphome/nspanel_esphome_addon_upload_tft.yaml  # Upload TFT add-on

esp32:
  framework:
    type: esp-idf

    