substitutions:
  name: "shelly-plus-1-mini-doorbell"
  device_name: "Shelly Plus 1 Mini (Doorbell)"

<<: !include templates/shelly-plus-1-mini.yaml

button:
  - platform: template
    id: "relay"
    name: "Ringdoor Relay"
    on_press: 
      then:
        - if:
            condition:
              - switch.is_off: "ringdoor_mute"
            then:
              - output.turn_on: "relay_output"
              - delay: 500ms
              - output.turn_off: "relay_output"
    icon: mdi:bell

switch:
  - platform: template
    id: "ringdoor_mute"
    name: "Ringdoor Mute"
    optimistic: True
    icon: mdi:bell-off

# Following code is not used because we are now using G4 Doorbell Pro PoE
binary_sensor:
  - platform: gpio
    name: "Ringdoor Switch"
    pin: 10
    on_state:
      then:
        - if:
            condition:
            - switch.is_off: "ringdoor_mute"
            then:
              - button.press: "relay"
    on_press:
      then:
        - homeassistant.event: 
            event: "esphome.ringdoor_pressed"
    filters:
      - delayed_on_off: 50ms
    